# Generated by Django 5.2.7 on 2025-10-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='英語名（小文字）', max_length=50, unique=True, verbose_name='感情名')),
                ('name_ja', models.CharField(max_length=50, verbose_name='感情名（日本語）')),
            ],
            options={
                'verbose_name': '感情',
                'verbose_name_plural': '感情',
                'db_table': 'emotions',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_emotion_name')],
            },
        ),
    ]
