# Generated by Django 5.2.7 on 2025-10-31 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emotions', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(verbose_name='開始日時')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('patient_text', models.TextField(blank=True, help_text='STTで変換されたテキスト全文', null=True, verbose_name='患者発話テキスト')),
                ('ai_response_text', models.TextField(blank=True, help_text='LLMが生成した共感的応答', null=True, verbose_name='AI応答テキスト')),
                ('emotion_reason', models.TextField(blank=True, help_text='LLMが感情を選んだ理由', null=True, verbose_name='感情選定理由')),
                ('emotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='emotions.emotion', verbose_name='感情')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patients.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '会話セッション',
                'verbose_name_plural': '会話セッション',
                'db_table': 'conversation_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['patient', 'started_at'], name='idx_session_patient_started'), models.Index(fields=['emotion'], name='idx_session_emotion'), models.Index(fields=['started_at'], name='idx_session_started')],
            },
        ),
    ]
