# Generated by Django 5.2.7 on 2025-10-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='患者名')),
                ('email', models.EmailField(help_text='ログインIDとして使用', max_length=254, unique=True, verbose_name='メールアドレス')),
                ('password', models.CharField(help_text='bcryptでハッシュ化して保存', max_length=255, verbose_name='パスワード')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='性別')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='入院日')),
            ],
            options={
                'verbose_name': '患者',
                'verbose_name_plural': '患者',
                'db_table': 'patients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='idx_patient_email'), models.Index(fields=['created_at'], name='idx_patient_created')],
            },
        ),
    ]
